name: insta_image_viewer
description: A simple widget for full screen with swipe to dismiss, pinch & zoom.
version: 1.0.2
homepage: https://github.com/AgoraDesk-LocalMonero/insta-image-viewer

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
